//! # Canonical Error Code Catalog for Safeguard Core
//!
//! Total documented error codes: 270
//! Granularly categorized across 9 operational domains for Soroban smart contracts.

#![allow(dead_code)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum ErrorDomain {
    HostEnvironment = 1,
    PolicyEngine = 2,
    PaymentRouting = 3,
    EscrowSettlement = 4,
    IdentityScreening = 5,
    AuthGovernance = 6,
    ClientSdk = 7,
    AuditIntegrity = 8,
    ConfigDeployment = 9,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ErrorDetail {
    pub code: u32,
    pub mnemonic: &'static str,
    pub domain: ErrorDomain,
    pub http_status: u16,
    pub description: &'static str,
}

pub const TOTAL_ERROR_CODES: usize = 270;

pub static ERROR_CATALOG: [ErrorDetail; 270] = [
    ErrorDetail {
        code: 1000,
        mnemonic: "HOST_BUDGET_EXCEEDED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Soroban CPU or memory instruction budget exhausted during invocation",
    },
    ErrorDetail {
        code: 1001,
        mnemonic: "INVALID_LEDGER_SEQUENCE",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Transaction submitted against an expired or future ledger sequence number",
    },
    ErrorDetail {
        code: 1002,
        mnemonic: "REENTRANCY_DETECTED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 409,
        description: "Cross-contract call recursion detected in policy-guarded execution",
    },
    ErrorDetail {
        code: 1003,
        mnemonic: "STORAGE_FOOTPRINT_EXCEEDED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Transaction footprint exceeds maximum ledger entry read/write limits",
    },
    ErrorDetail {
        code: 1004,
        mnemonic: "ENTRY_TTL_EXPIRED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 410,
        description: "Target contract instance or storage entry TTL has expired and needs archival restoration",
    },
    ErrorDetail {
        code: 1005,
        mnemonic: "HOST_OBJECT_HANDLE_INVALID",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Host object reference is dangling or corrupted in Soroban runtime",
    },
    ErrorDetail {
        code: 1006,
        mnemonic: "HOST_WASM_PARSE_FAILURE",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "WASM bytecode failed static verification on host runtime",
    },
    ErrorDetail {
        code: 1007,
        mnemonic: "STACK_OVERFLOW",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Soroban VM call stack depth limit reached",
    },
    ErrorDetail {
        code: 1008,
        mnemonic: "OUT_OF_GAS",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Resource fee paid insufficient for instruction units consumed",
    },
    ErrorDetail {
        code: 1009,
        mnemonic: "ARITHMETIC_OVERFLOW",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Integer overflow occurred during host mathematical evaluation",
    },
    ErrorDetail {
        code: 1010,
        mnemonic: "ARITHMETIC_UNDERFLOW",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Integer underflow occurred during balance deduction",
    },
    ErrorDetail {
        code: 1011,
        mnemonic: "DIVISION_BY_ZERO",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Attempted division by zero in fee or weight calculation",
    },
    ErrorDetail {
        code: 1012,
        mnemonic: "UNREGISTERED_CONTRACT",
        domain: ErrorDomain::HostEnvironment,
        http_status: 404,
        description: "Target contract address does not exist on the current ledger",
    },
    ErrorDetail {
        code: 1013,
        mnemonic: "INVALID_CONTRACT_TYPE",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "UDT contract type deserialization failed for payload",
    },
    ErrorDetail {
        code: 1014,
        mnemonic: "STORAGE_KEY_COLLISION",
        domain: ErrorDomain::HostEnvironment,
        http_status: 409,
        description: "Instance storage key already exists in write set",
    },
    ErrorDetail {
        code: 1015,
        mnemonic: "FOOTPRINT_READ_ONLY_VIOLATION",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Attempted write to a ledger entry marked read-only in footprint",
    },
    ErrorDetail {
        code: 1016,
        mnemonic: "HOST_CPU_LIMIT_REACHED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "CPU instruction count hit hard ledger cap",
    },
    ErrorDetail {
        code: 1017,
        mnemonic: "HOST_MEMORY_LIMIT_REACHED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Host memory allocation exceeded byte cap",
    },
    ErrorDetail {
        code: 1018,
        mnemonic: "CROSS_CALL_DEPTH_EXCEEDED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Cross-contract invocation depth exceeded limit of 10",
    },
    ErrorDetail {
        code: 1019,
        mnemonic: "EVENT_PAYLOAD_TOO_LARGE",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Contract event emission exceeds maximum payload size",
    },
    ErrorDetail {
        code: 1020,
        mnemonic: "INVALID_CONTRACT_ID_FORMAT",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Contract ID is not a valid 32-byte hex or C... StrKey",
    },
    ErrorDetail {
        code: 1021,
        mnemonic: "LEDGER_TIMESTAMP_DRIFT",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Ledger timestamp is outside expected acceptable drift window",
    },
    ErrorDetail {
        code: 1022,
        mnemonic: "SOROBAN_INTERNAL_ERROR",
        domain: ErrorDomain::HostEnvironment,
        http_status: 500,
        description: "Unhandled internal error inside host environment",
    },
    ErrorDetail {
        code: 1023,
        mnemonic: "RESOURCE_FEE_BELOW_MINIMUM",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Supplied resource fee does not satisfy network minimum base fee",
    },
    ErrorDetail {
        code: 1024,
        mnemonic: "TRANSACTION_MALFORMED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 400,
        description: "Host failed to parse envelope XDR structure",
    },
    ErrorDetail {
        code: 1025,
        mnemonic: "INVALID_SOURCE_ACCOUNT",
        domain: ErrorDomain::HostEnvironment,
        http_status: 404,
        description: "Transaction source account is not funded on testnet/mainnet",
    },
    ErrorDetail {
        code: 1026,
        mnemonic: "SIGNATURE_VERIFICATION_FAILED",
        domain: ErrorDomain::HostEnvironment,
        http_status: 401,
        description: "Cryptographic signature does not match public key in envelope",
    },
    ErrorDetail {
        code: 1027,
        mnemonic: "NONCE_MISMATCH",
        domain: ErrorDomain::HostEnvironment,
        http_status: 409,
        description: "Account sequence number does not increment prior ledger state",
    },
    ErrorDetail {
        code: 1028,
        mnemonic: "UNSUPPORTED_HOST_FUNCTION",
        domain: ErrorDomain::HostEnvironment,
        http_status: 501,
        description: "Host function is not available in current protocol version",
    },
    ErrorDetail {
        code: 1029,
        mnemonic: "STORAGE_ENTRY_NOT_FOUND",
        domain: ErrorDomain::HostEnvironment,
        http_status: 404,
        description: "Target key does not exist in instance or persistent storage",
    },
    ErrorDetail {
        code: 2000,
        mnemonic: "POLICY_NOT_ACTIVE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Compliance policy exists but is currently deactivated",
    },
    ErrorDetail {
        code: 2001,
        mnemonic: "POLICY_NOT_FOUND",
        domain: ErrorDomain::PolicyEngine,
        http_status: 404,
        description: "No compliance policy registered for the requested token or identifier",
    },
    ErrorDetail {
        code: 2002,
        mnemonic: "POLICY_ALREADY_EXISTS",
        domain: ErrorDomain::PolicyEngine,
        http_status: 409,
        description: "A policy with this identifier has already been registered",
    },
    ErrorDetail {
        code: 2003,
        mnemonic: "RULE_PRECEDENCE_MISMATCH",
        domain: ErrorDomain::PolicyEngine,
        http_status: 422,
        description: "Evaluation precedence conflicting between blocking and flagging rules",
    },
    ErrorDetail {
        code: 2004,
        mnemonic: "RULE_EVALUATION_TIMEOUT",
        domain: ErrorDomain::PolicyEngine,
        http_status: 504,
        description: "Deterministic evaluation exceeded cycle limit",
    },
    ErrorDetail {
        code: 2005,
        mnemonic: "ALLOWLIST_REQUIRED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Sender or recipient is not present in approved allowlist registry",
    },
    ErrorDetail {
        code: 2006,
        mnemonic: "DENYLIST_MATCHED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Account is explicitly designated on an active denylist",
    },
    ErrorDetail {
        code: 2007,
        mnemonic: "SANCTIONS_MATCHED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Target entity matched an active international sanctions dataset",
    },
    ErrorDetail {
        code: 2008,
        mnemonic: "JURISDICTION_PROHIBITED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Transaction originates from or terminates in an embargoed jurisdiction",
    },
    ErrorDetail {
        code: 2009,
        mnemonic: "JURISDICTION_UNKNOWN",
        domain: ErrorDomain::PolicyEngine,
        http_status: 422,
        description: "Account jurisdiction code is undefined in regional compliance map",
    },
    ErrorDetail {
        code: 2010,
        mnemonic: "ACCOUNT_FROZEN",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Account has been frozen by regulatory administrator",
    },
    ErrorDetail {
        code: 2011,
        mnemonic: "POLICY_VERSION_DEPRECATED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 410,
        description: "Policy version has been superseded by a newer version",
    },
    ErrorDetail {
        code: 2012,
        mnemonic: "RULE_PAYLOAD_CORRUPTED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 500,
        description: "Rule record serialization in contract storage failed checksum",
    },
    ErrorDetail {
        code: 2013,
        mnemonic: "INVALID_ACTION_CODE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Action code must be one of APPROVE (1), FLAG (2), or BLOCK (3)",
    },
    ErrorDetail {
        code: 2014,
        mnemonic: "INVALID_RULE_TYPE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Rule type is not recognized by the evaluation engine",
    },
    ErrorDetail {
        code: 2015,
        mnemonic: "DUPLICATE_RULE_ID",
        domain: ErrorDomain::PolicyEngine,
        http_status: 409,
        description: "Rule ID already exists within the target policy version",
    },
    ErrorDetail {
        code: 2016,
        mnemonic: "MAX_RULES_EXCEEDED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Policy version exceeds maximum limit of 256 rule records",
    },
    ErrorDetail {
        code: 2017,
        mnemonic: "POLICY_HASH_MISMATCH",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Supplied policy configuration hash does not match computed digest",
    },
    ErrorDetail {
        code: 2018,
        mnemonic: "TOKEN_NOT_BOUND",
        domain: ErrorDomain::PolicyEngine,
        http_status: 404,
        description: "Token contract address is not bound to this compliance policy",
    },
    ErrorDetail {
        code: 2019,
        mnemonic: "TOKEN_ALREADY_BOUND",
        domain: ErrorDomain::PolicyEngine,
        http_status: 409,
        description: "Token is already bound to another active compliance policy",
    },
    ErrorDetail {
        code: 2020,
        mnemonic: "RULE_PREDICATE_EVAL_ERROR",
        domain: ErrorDomain::PolicyEngine,
        http_status: 500,
        description: "Dynamic evaluation of rule predicate returned unexpected error",
    },
    ErrorDetail {
        code: 2021,
        mnemonic: "CONDITIONAL_FLAG_TRIGGERED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 202,
        description: "Transaction flagged for asynchronous compliance team investigation",
    },
    ErrorDetail {
        code: 2022,
        mnemonic: "SANCTIONS_DATASET_EXPIRED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 422,
        description: "On-chain sanctions snapshot has lapsed its validity epoch",
    },
    ErrorDetail {
        code: 2023,
        mnemonic: "ALLOWLIST_MEMBERSHIP_EXPIRED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Subject allowlist verification validity period has lapsed",
    },
    ErrorDetail {
        code: 2024,
        mnemonic: "HIGH_RISK_CORRIDOR_BLOCKED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Corridor between source and destination jurisdiction is prohibited",
    },
    ErrorDetail {
        code: 2025,
        mnemonic: "VOLUME_VELOCITY_EXCEEDED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 429,
        description: "Account cumulative transfer volume exceeded 24-hour limit",
    },
    ErrorDetail {
        code: 2026,
        mnemonic: "DAILY_TRANSACTION_COUNT_CAP",
        domain: ErrorDomain::PolicyEngine,
        http_status: 429,
        description: "Daily transaction frequency limit reached for account tier",
    },
    ErrorDetail {
        code: 2027,
        mnemonic: "INELIGIBLE_FOR_AUTO_APPROVE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Transaction attributes require manual compliance sign-off",
    },
    ErrorDetail {
        code: 2028,
        mnemonic: "POLICY_SUSPENDED_BY_CIRCUIT_BREAKER",
        domain: ErrorDomain::PolicyEngine,
        http_status: 503,
        description: "Circuit breaker tripped due to anomalous high failure rate",
    },
    ErrorDetail {
        code: 2029,
        mnemonic: "INVALID_EVALUATION_INPUT",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Input payload passed to evaluate() is missing required subject fields",
    },
    ErrorDetail {
        code: 2030,
        mnemonic: "POLICY_BINDING_REVOKED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 403,
        description: "Policy binding was revoked by asset issuer",
    },
    ErrorDetail {
        code: 2031,
        mnemonic: "UNRECOGNIZED_POLICY_EVENT",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Policy contract emitted an unhandled lifecycle event code",
    },
    ErrorDetail {
        code: 2032,
        mnemonic: "MERKLE_ROOT_UNINITIALIZED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 404,
        description: "Sanctions merkle tree root has not been initialized",
    },
    ErrorDetail {
        code: 2033,
        mnemonic: "UNAUTHORIZED_REGISTRY_UPDATE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 401,
        description: "Caller does not hold the Registry Authority capability",
    },
    ErrorDetail {
        code: 2034,
        mnemonic: "POLICY_NAME_TOO_LONG",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Policy name string exceeds 64 byte storage limit",
    },
    ErrorDetail {
        code: 2035,
        mnemonic: "CONFLICTING_RULE_DIRECTIVE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 409,
        description: "Two matching rules emit contradictory actions at same priority",
    },
    ErrorDetail {
        code: 2036,
        mnemonic: "THRESHOLD_WEIGHT_INVALID",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Rule evaluation score threshold is non-monotonic",
    },
    ErrorDetail {
        code: 2037,
        mnemonic: "REASON_CODE_UNKNOWN",
        domain: ErrorDomain::PolicyEngine,
        http_status: 400,
        description: "Evaluation emitted an unmapped reason code",
    },
    ErrorDetail {
        code: 2038,
        mnemonic: "POLICY_LOCKED_PENDING_UPGRADE",
        domain: ErrorDomain::PolicyEngine,
        http_status: 423,
        description: "Policy contract is temporarily locked during version transition",
    },
    ErrorDetail {
        code: 2039,
        mnemonic: "REGISTRY_COMPACT_REQUIRED",
        domain: ErrorDomain::PolicyEngine,
        http_status: 507,
        description: "Persistent registry size exceeds memory threshold; requires compaction",
    },
    ErrorDetail {
        code: 3000,
        mnemonic: "INSUFFICIENT_BALANCE",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Sender has insufficient balance to complete payment",
    },
    ErrorDetail {
        code: 3001,
        mnemonic: "SAC_INVOCATION_FAILED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 502,
        description: "Stellar Asset Contract transfer invocation returned error",
    },
    ErrorDetail {
        code: 3002,
        mnemonic: "INVALID_DECIMAL_PRECISION",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Amount exceeds token decimal precision (maximum 7 decimals for SAC)",
    },
    ErrorDetail {
        code: 3003,
        mnemonic: "UNAUTHORIZED_TRANSFER_FROM",
        domain: ErrorDomain::PaymentRouting,
        http_status: 401,
        description: "Contract does not have allowance to debit tokens from sender",
    },
    ErrorDetail {
        code: 3004,
        mnemonic: "SPEND_CAP_EXCEEDED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Transaction amount exceeds instantaneous spend cap threshold",
    },
    ErrorDetail {
        code: 3005,
        mnemonic: "SLIPPAGE_EXCEEDED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Price slippage exceeded user tolerance during payment swap",
    },
    ErrorDetail {
        code: 3006,
        mnemonic: "FEE_EXCEEDS_ALLOWANCE",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment routing fee exceeds configured maximum limit",
    },
    ErrorDetail {
        code: 3007,
        mnemonic: "ZERO_AMOUNT_PAYMENT",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment amount must be strictly greater than zero",
    },
    ErrorDetail {
        code: 3008,
        mnemonic: "NEGATIVE_AMOUNT_PAYMENT",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Negative payment amount is invalid",
    },
    ErrorDetail {
        code: 3009,
        mnemonic: "TOKEN_NOT_ACCEPTABLE",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Asset is not in the list of accepted settlement currencies",
    },
    ErrorDetail {
        code: 3010,
        mnemonic: "RECIPIENT_DENYLISTED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 403,
        description: "Payment recipient address is marked on active denylist",
    },
    ErrorDetail {
        code: 3011,
        mnemonic: "SENDER_DENYLISTED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 403,
        description: "Payment sender address is marked on active denylist",
    },
    ErrorDetail {
        code: 3012,
        mnemonic: "CIRCULAR_PAYMENT_LOOP",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment route forms an invalid cyclic self-transfer",
    },
    ErrorDetail {
        code: 3013,
        mnemonic: "MAX_PAYMENT_SIZE_EXCEEDED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment exceeds maximum protocol payment size cap",
    },
    ErrorDetail {
        code: 3014,
        mnemonic: "MIN_PAYMENT_SIZE_VIOLATED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment is smaller than network dust threshold",
    },
    ErrorDetail {
        code: 3015,
        mnemonic: "SAC_CONTRACT_NOT_FOUND",
        domain: ErrorDomain::PaymentRouting,
        http_status: 404,
        description: "Stellar Asset Contract for given asset code not deployed on network",
    },
    ErrorDetail {
        code: 3016,
        mnemonic: "PAYMENT_MEMO_TOO_LONG",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment transaction memo exceeds maximum byte length (28 bytes text)",
    },
    ErrorDetail {
        code: 3017,
        mnemonic: "MEMO_REQUIRED_BY_RECIPIENT",
        domain: ErrorDomain::PaymentRouting,
        http_status: 422,
        description: "Recipient address is an exchange or custodial gateway requiring a memo",
    },
    ErrorDetail {
        code: 3018,
        mnemonic: "EXCHANGE_RATE_EXPIRED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 408,
        description: "Asset conversion rate quote has expired",
    },
    ErrorDetail {
        code: 3019,
        mnemonic: "CROSS_CURRENCY_PATH_NOT_FOUND",
        domain: ErrorDomain::PaymentRouting,
        http_status: 404,
        description: "No liquidity pool path found between source and destination assets",
    },
    ErrorDetail {
        code: 3020,
        mnemonic: "ROUTING_HOP_LIMIT_EXCEEDED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment routing path exceeds maximum allowable hops (limit 3)",
    },
    ErrorDetail {
        code: 3021,
        mnemonic: "SETTLEMENT_CURRENCY_MISMATCH",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Settlement currency received does not match merchant requirement",
    },
    ErrorDetail {
        code: 3022,
        mnemonic: "MERCHANT_FEE_OVER_LIMIT",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Calculated merchant processing fee exceeds ceiling",
    },
    ErrorDetail {
        code: 3023,
        mnemonic: "TOKEN_DECIMALS_MISMATCH",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Decimals provided do not match asset contract specifications",
    },
    ErrorDetail {
        code: 3024,
        mnemonic: "PARTIAL_PAYMENT_REJECTED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Merchant configuration does not allow underpayments",
    },
    ErrorDetail {
        code: 3025,
        mnemonic: "OVERPAYMENT_EXCEEDS_BUFFER",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Payment amount exceeds invoice amount beyond allowed buffer",
    },
    ErrorDetail {
        code: 3026,
        mnemonic: "INVOICE_EXPIRED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 410,
        description: "Payment invoice has expired and can no longer be settled",
    },
    ErrorDetail {
        code: 3027,
        mnemonic: "INVOICE_ALREADY_PAID",
        domain: ErrorDomain::PaymentRouting,
        http_status: 409,
        description: "Payment invoice has already been settled",
    },
    ErrorDetail {
        code: 3028,
        mnemonic: "PAYMENT_NONCE_REUSED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 409,
        description: "Unique payment reference nonce has already been consumed",
    },
    ErrorDetail {
        code: 3029,
        mnemonic: "LIQUIDITY_POOL_FROZEN",
        domain: ErrorDomain::PaymentRouting,
        http_status: 503,
        description: "Target liquidity pool is temporarily paused by administrator",
    },
    ErrorDetail {
        code: 3030,
        mnemonic: "CURRENCY_CORRIDOR_DISABLED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 403,
        description: "Direct payment corridor between currency pair is disabled",
    },
    ErrorDetail {
        code: 3031,
        mnemonic: "UNSUPPORTED_ASSET_TYPE",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Asset type is not supported (only SAC and Native XLM supported)",
    },
    ErrorDetail {
        code: 3032,
        mnemonic: "UNAUTHORIZED_ASSET_ISSUER",
        domain: ErrorDomain::PaymentRouting,
        http_status: 401,
        description: "Asset issuer is not authorized on compliance registry",
    },
    ErrorDetail {
        code: 3033,
        mnemonic: "PAYMENT_EXECUTION_FAILED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 500,
        description: "Payment execution reverted during atomic batch settlement",
    },
    ErrorDetail {
        code: 3034,
        mnemonic: "REFUND_TIMELOCK_ACTIVE",
        domain: ErrorDomain::PaymentRouting,
        http_status: 423,
        description: "Payment refund cannot be processed until refund delay passes",
    },
    ErrorDetail {
        code: 3035,
        mnemonic: "ALREADY_REFUNDED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 409,
        description: "Payment transaction has already been refunded",
    },
    ErrorDetail {
        code: 3036,
        mnemonic: "REFUND_AMOUNT_EXCEEDS_ORIGINAL",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Requested refund amount exceeds original settlement amount",
    },
    ErrorDetail {
        code: 3037,
        mnemonic: "SPLIT_PAYMENT_MISALLOCATION",
        domain: ErrorDomain::PaymentRouting,
        http_status: 400,
        description: "Split recipient shares do not sum to 10,000 basis points",
    },
    ErrorDetail {
        code: 3038,
        mnemonic: "MERCHANT_ACCOUNT_DEACTIVATED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 403,
        description: "Merchant receiver account is deactivated or closed",
    },
    ErrorDetail {
        code: 3039,
        mnemonic: "TREASURY_ACCOUNT_DRAINED",
        domain: ErrorDomain::PaymentRouting,
        http_status: 503,
        description: "Fee rebate treasury has insufficient balance to sponsor gas",
    },
    ErrorDetail {
        code: 4000,
        mnemonic: "ESCROW_NOT_FOUND",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 404,
        description: "Escrow record with given ID does not exist",
    },
    ErrorDetail {
        code: 4001,
        mnemonic: "ESCROW_ALREADY_SETTLED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "Escrow has already been released to recipient",
    },
    ErrorDetail {
        code: 4002,
        mnemonic: "ESCROW_ALREADY_REFUNDED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "Escrow has already been returned to depositor",
    },
    ErrorDetail {
        code: 4003,
        mnemonic: "ESCROW_TIMELOCK_ACTIVE",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 423,
        description: "Escrow release condition timelock has not yet expired",
    },
    ErrorDetail {
        code: 4004,
        mnemonic: "ARBITER_UNAUTHORIZED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 401,
        description: "Signer is not the designated arbiter for this escrow",
    },
    ErrorDetail {
        code: 4005,
        mnemonic: "DISPUTE_WINDOW_EXPIRED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Window for lodging an escrow dispute has closed",
    },
    ErrorDetail {
        code: 4006,
        mnemonic: "DISPUTE_ALREADY_LOGGED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "A dispute has already been filed for this escrow",
    },
    ErrorDetail {
        code: 4007,
        mnemonic: "ESCROW_DEPOSIT_MISMATCH",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Deposited amount does not match escrow terms",
    },
    ErrorDetail {
        code: 4008,
        mnemonic: "PARTIAL_RELEASE_UNSUPPORTED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Escrow contract terms require full atomic release",
    },
    ErrorDetail {
        code: 4009,
        mnemonic: "ESCROW_RELEASE_FAILED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 500,
        description: "Transfer from escrow vault contract to beneficiary failed",
    },
    ErrorDetail {
        code: 4010,
        mnemonic: "INSUFFICIENT_ESCROW_COLLATERAL",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Collateral deposit is below required liquidation ratio",
    },
    ErrorDetail {
        code: 4011,
        mnemonic: "COLLATERAL_ALREADY_CLAIMED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "Escrow collateral has already been claimed by counterparty",
    },
    ErrorDetail {
        code: 4012,
        mnemonic: "TIMELOCK_EXCEEDS_MAXIMUM",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Requested timelock duration exceeds maximum policy ceiling (1 year)",
    },
    ErrorDetail {
        code: 4013,
        mnemonic: "TIMELOCK_BELOW_MINIMUM",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Requested timelock duration is below minimum cooling period (1 hour)",
    },
    ErrorDetail {
        code: 4014,
        mnemonic: "UNAUTHORIZED_DEPOSITOR",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 401,
        description: "Signer is not authorized as the depositor for this escrow",
    },
    ErrorDetail {
        code: 4015,
        mnemonic: "UNAUTHORIZED_BENEFICIARY",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 401,
        description: "Signer is not authorized as beneficiary to claim escrow",
    },
    ErrorDetail {
        code: 4016,
        mnemonic: "ESCROW_EXPIRED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 410,
        description: "Escrow validity duration has elapsed without fulfillment",
    },
    ErrorDetail {
        code: 4017,
        mnemonic: "CONDITION_PROOF_INVALID",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 422,
        description: "Cryptographic preimage or oracle proof failed verification",
    },
    ErrorDetail {
        code: 4018,
        mnemonic: "HASH_LOCK_MISMATCH",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Supplied secret does not match SHA-256 hash lock commitment",
    },
    ErrorDetail {
        code: 4019,
        mnemonic: "ORACLE_ATTESTATION_EXPIRED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 408,
        description: "External oracle attestation timestamp has expired",
    },
    ErrorDetail {
        code: 4020,
        mnemonic: "UNTRUSTED_ORACLE_SIGNER",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 401,
        description: "Attestation signature does not match trusted oracle registry",
    },
    ErrorDetail {
        code: 4021,
        mnemonic: "MULTI_PARTY_SIG_INCOMPLETE",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Escrow release requires M-of-N threshold signatures",
    },
    ErrorDetail {
        code: 4022,
        mnemonic: "ESCROW_CANCELLED_BY_ADMIN",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 403,
        description: "Escrow was cancelled by emergency administration override",
    },
    ErrorDetail {
        code: 4023,
        mnemonic: "DUPLICATE_ESCROW_ID",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "Escrow ID already exists in storage registry",
    },
    ErrorDetail {
        code: 4024,
        mnemonic: "ESCROW_VAULT_PAUSED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 503,
        description: "Escrow operations paused during protocol upgrade",
    },
    ErrorDetail {
        code: 4025,
        mnemonic: "INSPECTION_PERIOD_ACTIVE",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 423,
        description: "Funds cannot be released while buyer inspection period is active",
    },
    ErrorDetail {
        code: 4026,
        mnemonic: "MILESTONE_NOT_COMPLETED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Escrow tranche milestone has not been verified by inspector",
    },
    ErrorDetail {
        code: 4027,
        mnemonic: "MILESTONE_INDEX_OUT_OF_BOUNDS",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Milestone index exceeds defined tranche count",
    },
    ErrorDetail {
        code: 4028,
        mnemonic: "TRANCHE_ALREADY_RELEASED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 409,
        description: "Target milestone tranche has already been paid out",
    },
    ErrorDetail {
        code: 4029,
        mnemonic: "ARBITRATION_FEE_UNPAID",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 402,
        description: "Filing dispute requires prepayment of arbitration fee",
    },
    ErrorDetail {
        code: 4030,
        mnemonic: "SETTLEMENT_SPLIT_OVERFLOW",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 400,
        description: "Arbiter split ratio between parties exceeds 100%",
    },
    ErrorDetail {
        code: 4031,
        mnemonic: "AUTOMATIC_EXPIRATION_DISABLED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 403,
        description: "Escrow configuration does not permit permissionless expiration",
    },
    ErrorDetail {
        code: 4032,
        mnemonic: "BUYER_REJECTION_RECORDED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 403,
        description: "Buyer has recorded formal rejection of goods",
    },
    ErrorDetail {
        code: 4033,
        mnemonic: "ESCROW_STATE_CORRUPTED",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 500,
        description: "Escrow state machine transitioned into an undefined state",
    },
    ErrorDetail {
        code: 4034,
        mnemonic: "RECOVERY_TIMELOCK_PENDING",
        domain: ErrorDomain::EscrowSettlement,
        http_status: 423,
        description: "Emergency funds recovery timelock (30 days) is still active",
    },
    ErrorDetail {
        code: 5000,
        mnemonic: "SUBJECT_UNVERIFIED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Identity proof for subject account has not been verified",
    },
    ErrorDetail {
        code: 5001,
        mnemonic: "SPECIALLY_DESIGNATED_NATIONAL",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Account is designated on OFAC SDN sanctions list",
    },
    ErrorDetail {
        code: 5002,
        mnemonic: "SECONDARY_SANCTIONS_RISK",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Transaction presents secondary sanctions exposure risk",
    },
    ErrorDetail {
        code: 5003,
        mnemonic: "KYC_PROOF_EXPIRED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Identity credential has expired and must be reverified",
    },
    ErrorDetail {
        code: 5004,
        mnemonic: "MERKLE_PROOF_INVALID",
        domain: ErrorDomain::IdentityScreening,
        http_status: 422,
        description: "Cryptographic inclusion proof failed against on-chain root",
    },
    ErrorDetail {
        code: 5005,
        mnemonic: "PEP_DETECTED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Politically Exposed Person detected requiring enhanced due diligence",
    },
    ErrorDetail {
        code: 5006,
        mnemonic: "ADVERSE_MEDIA_FLAG",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Entity flagged in global adverse media screening database",
    },
    ErrorDetail {
        code: 5007,
        mnemonic: "HIGH_RISK_JURISDICTION",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Entity associated with FATF high-risk monitored jurisdiction",
    },
    ErrorDetail {
        code: 5008,
        mnemonic: "IDENTITY_PROVIDER_UNTRUSTED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Identity attestation signed by uncertified KYC issuer",
    },
    ErrorDetail {
        code: 5009,
        mnemonic: "CREDENTIAL_REVOKED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Identity credential was revoked by the issuing authority",
    },
    ErrorDetail {
        code: 5010,
        mnemonic: "DID_RESOLVER_UNAVAILABLE",
        domain: ErrorDomain::IdentityScreening,
        http_status: 503,
        description: "Decentralized Identifier resolver endpoint timed out",
    },
    ErrorDetail {
        code: 5011,
        mnemonic: "INVALID_CREDENTIAL_SIGNATURE",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "W3C Verifiable Credential signature verification failed",
    },
    ErrorDetail {
        code: 5012,
        mnemonic: "SUBJECT_ADDRESS_MISMATCH",
        domain: ErrorDomain::IdentityScreening,
        http_status: 400,
        description: "Attestation subject address does not match transaction sender",
    },
    ErrorDetail {
        code: 5013,
        mnemonic: "SANCTIONS_LIST_UPDATE_STALE",
        domain: ErrorDomain::IdentityScreening,
        http_status: 422,
        description: "On-chain sanctions list has not been updated within 24h",
    },
    ErrorDetail {
        code: 5014,
        mnemonic: "FUZZY_NAME_MATCH_AMBIGUOUS",
        domain: ErrorDomain::IdentityScreening,
        http_status: 422,
        description: "Fuzzy screening match score falls in ambiguous review zone",
    },
    ErrorDetail {
        code: 5015,
        mnemonic: "ENTITY_REGISTRATION_INVALID",
        domain: ErrorDomain::IdentityScreening,
        http_status: 400,
        description: "Corporate entity LEI or registration number is invalid",
    },
    ErrorDetail {
        code: 5016,
        mnemonic: "TRAVEL_RULE_PAYLOAD_MISSING",
        domain: ErrorDomain::IdentityScreening,
        http_status: 422,
        description: "Transfer exceeds $3,000 threshold requiring Travel Rule IVMS101 data",
    },
    ErrorDetail {
        code: 5017,
        mnemonic: "TRAVEL_RULE_VASP_UNVERIFIED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Counterparty VASP is not registered on trusted directory",
    },
    ErrorDetail {
        code: 5018,
        mnemonic: "BENEFICIARY_INFO_INCOMPLETE",
        domain: ErrorDomain::IdentityScreening,
        http_status: 400,
        description: "Beneficiary physical address or date of birth missing in payload",
    },
    ErrorDetail {
        code: 5019,
        mnemonic: "IDENTITY_COMMITMENT_EXISTS",
        domain: ErrorDomain::IdentityScreening,
        http_status: 409,
        description: "A credential has already been committed for this account",
    },
    ErrorDetail {
        code: 5020,
        mnemonic: "ZERO_KNOWLEDGE_PROOF_REJECTED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 422,
        description: "zk-SNARK compliance proof verification failed on-chain",
    },
    ErrorDetail {
        code: 5021,
        mnemonic: "ANONYMOUS_PROXY_DETECTED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Transaction originated from known VPN/TOR exit node or mixing pool",
    },
    ErrorDetail {
        code: 5022,
        mnemonic: "AGE_VERIFICATION_FAILED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Signer does not satisfy minimum age requirement (18+)",
    },
    ErrorDetail {
        code: 5023,
        mnemonic: "RESIDENCY_ATTESTATION_MISSING",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Proof of residency required for this regulatory jurisdiction",
    },
    ErrorDetail {
        code: 5024,
        mnemonic: "WATCHLIST_NAME_SIMILARITY",
        domain: ErrorDomain::IdentityScreening,
        http_status: 202,
        description: "Name similarity score exceeds alert threshold; flagged for review",
    },
    ErrorDetail {
        code: 5025,
        mnemonic: "IP_GEOLOCATION_MISMATCH",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Sender IP geolocation conflicts with registered KYC jurisdiction",
    },
    ErrorDetail {
        code: 5026,
        mnemonic: "BIOMETRIC_LIVENESS_FAILED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 401,
        description: "Biometric face match liveness verification expired or failed",
    },
    ErrorDetail {
        code: 5027,
        mnemonic: "DUAL_NATIONALITY_SANCTIONED",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Individual holds secondary nationality in sanctioned territory",
    },
    ErrorDetail {
        code: 5028,
        mnemonic: "MILITARY_END_USER_RESTRICTION",
        domain: ErrorDomain::IdentityScreening,
        http_status: 403,
        description: "Recipient entity flagged under Military End-User regulations",
    },
    ErrorDetail {
        code: 5029,
        mnemonic: "COMPLIANCE_HOLD_PENDING",
        domain: ErrorDomain::IdentityScreening,
        http_status: 423,
        description: "Compliance hold placed on account pending regulatory inquiry",
    },
    ErrorDetail {
        code: 6000,
        mnemonic: "UNAUTHORIZED_CALLER",
        domain: ErrorDomain::AuthGovernance,
        http_status: 401,
        description: "Signer does not hold authorization to execute this function",
    },
    ErrorDetail {
        code: 6001,
        mnemonic: "ADMIN_KEY_REVOKED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 401,
        description: "Admin key has been revoked and replaced by multi-sig governance",
    },
    ErrorDetail {
        code: 6002,
        mnemonic: "SIGNATURE_THRESHOLD_UNMET",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Collected signatures do not meet multi-sig quorum threshold",
    },
    ErrorDetail {
        code: 6003,
        mnemonic: "EMERGENCY_PAUSE_ACTIVE",
        domain: ErrorDomain::AuthGovernance,
        http_status: 503,
        description: "Contract is currently in Emergency Pause mode",
    },
    ErrorDetail {
        code: 6004,
        mnemonic: "UPGRADE_UNAUTHORIZED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 401,
        description: "Caller does not possess Contract Upgrade capability",
    },
    ErrorDetail {
        code: 6005,
        mnemonic: "TIMELOCK_DELAY_NOT_MET",
        domain: ErrorDomain::AuthGovernance,
        http_status: 423,
        description: "Governance proposal time-delay has not elapsed",
    },
    ErrorDetail {
        code: 6006,
        mnemonic: "PROPOSAL_ALREADY_EXECUTED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 409,
        description: "Governance proposal has already been executed",
    },
    ErrorDetail {
        code: 6007,
        mnemonic: "PROPOSAL_CANCELLED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 410,
        description: "Governance proposal was cancelled by emergency multisig",
    },
    ErrorDetail {
        code: 6008,
        mnemonic: "PROPOSAL_VOTING_CLOSED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Voting window for governance proposal has closed",
    },
    ErrorDetail {
        code: 6009,
        mnemonic: "VOTE_ALREADY_CAST",
        domain: ErrorDomain::AuthGovernance,
        http_status: 409,
        description: "Signer has already cast a vote on this proposal",
    },
    ErrorDetail {
        code: 6010,
        mnemonic: "INSUFFICIENT_VOTING_POWER",
        domain: ErrorDomain::AuthGovernance,
        http_status: 403,
        description: "Signer does not hold required governance token balance",
    },
    ErrorDetail {
        code: 6011,
        mnemonic: "ROLE_ALREADY_ASSIGNED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 409,
        description: "Target address already possesses the assigned role",
    },
    ErrorDetail {
        code: 6012,
        mnemonic: "ROLE_NOT_FOUND",
        domain: ErrorDomain::AuthGovernance,
        http_status: 404,
        description: "Target address does not hold the role to be revoked",
    },
    ErrorDetail {
        code: 6013,
        mnemonic: "SELF_REVOCATION_PREVENTED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Administrator cannot revoke their own final admin role",
    },
    ErrorDetail {
        code: 6014,
        mnemonic: "MULTISIG_WEIGHT_ZERO",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Signer weight cannot be zero in governance quorum",
    },
    ErrorDetail {
        code: 6015,
        mnemonic: "QUORUM_CEILING_EXCEEDED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Total quorum weight exceeds maximum allowable scale",
    },
    ErrorDetail {
        code: 6016,
        mnemonic: "REPLAY_NONCE_DETECTED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 409,
        description: "Cryptographic invocation nonce has already been used",
    },
    ErrorDetail {
        code: 6017,
        mnemonic: "EXPIRATION_TIME_IN_PAST",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Authorization delegation signature expiration is in the past",
    },
    ErrorDetail {
        code: 6018,
        mnemonic: "DELEGATION_SCOPE_EXCEEDED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 403,
        description: "Delegated key attempted operation outside allowed method scope",
    },
    ErrorDetail {
        code: 6019,
        mnemonic: "GAS_SPONSOR_REJECTED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 401,
        description: "Gas fee relayer rejected sponsorship for this transaction",
    },
    ErrorDetail {
        code: 6020,
        mnemonic: "CIRCUIT_BREAKER_TRIPPED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 503,
        description: "Automated circuit breaker tripped due to anomalous contract event",
    },
    ErrorDetail {
        code: 6021,
        mnemonic: "RATE_LIMIT_HIT",
        domain: ErrorDomain::AuthGovernance,
        http_status: 429,
        description: "Administrative invocation frequency exceeded per-minute limit",
    },
    ErrorDetail {
        code: 6022,
        mnemonic: "INVALID_GOVERNANCE_CONFIG",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "Governance parameters violate invariant constraints",
    },
    ErrorDetail {
        code: 6023,
        mnemonic: "GUARDIAN_COOLDOWN_ACTIVE",
        domain: ErrorDomain::AuthGovernance,
        http_status: 423,
        description: "Guardian key rotation is subject to a 7-day cooldown",
    },
    ErrorDetail {
        code: 6024,
        mnemonic: "BACKUP_KEY_NOT_CONFIGURED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 404,
        description: "Emergency recovery triggered but no backup key was registered",
    },
    ErrorDetail {
        code: 6025,
        mnemonic: "UPGRADE_HASH_MISMATCH",
        domain: ErrorDomain::AuthGovernance,
        http_status: 400,
        description: "WASM bytecode hash does not match hash approved in proposal",
    },
    ErrorDetail {
        code: 6026,
        mnemonic: "INITIALIZER_ALREADY_RUN",
        domain: ErrorDomain::AuthGovernance,
        http_status: 409,
        description: "Contract initialize() method can only be executed once",
    },
    ErrorDetail {
        code: 6027,
        mnemonic: "WRONG_CALL_CONTEXT",
        domain: ErrorDomain::AuthGovernance,
        http_status: 403,
        description: "Method can only be invoked from another contract via internal call",
    },
    ErrorDetail {
        code: 6028,
        mnemonic: "CROSS_ORG_CALL_UNAUTHORIZED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 401,
        description: "Cross-organization federation key not accepted",
    },
    ErrorDetail {
        code: 6029,
        mnemonic: "DEPUTY_PERMISSIONS_REVOKED",
        domain: ErrorDomain::AuthGovernance,
        http_status: 403,
        description: "Deputy operator permissions have been suspended",
    },
    ErrorDetail {
        code: 7000,
        mnemonic: "NETWORK_TIMEOUT",
        domain: ErrorDomain::ClientSdk,
        http_status: 504,
        description: "Soroban RPC network request timed out",
    },
    ErrorDetail {
        code: 7001,
        mnemonic: "RPC_NODE_UNREACHABLE",
        domain: ErrorDomain::ClientSdk,
        http_status: 503,
        description: "Configured Soroban RPC endpoint is offline or unreachable",
    },
    ErrorDetail {
        code: 7002,
        mnemonic: "SIMULATION_MISMATCH",
        domain: ErrorDomain::ClientSdk,
        http_status: 422,
        description: "On-chain execution diverged from local transaction simulation",
    },
    ErrorDetail {
        code: 7003,
        mnemonic: "XDR_DECODE_ERROR",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Failed to decode base64 XDR structure returned from RPC",
    },
    ErrorDetail {
        code: 7004,
        mnemonic: "RATE_LIMIT_EXCEEDED",
        domain: ErrorDomain::ClientSdk,
        http_status: 429,
        description: "RPC requests exceeded per-second quota",
    },
    ErrorDetail {
        code: 7005,
        mnemonic: "INVALID_ADDRESS_CHECKSUM",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Stellar StrKey address failed CRC16 checksum validation",
    },
    ErrorDetail {
        code: 7006,
        mnemonic: "MISSING_TRANSACTION_SIGNATURE",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Transaction envelope submitted without required signatures",
    },
    ErrorDetail {
        code: 7007,
        mnemonic: "HORIZON_FALLBACK_FAILED",
        domain: ErrorDomain::ClientSdk,
        http_status: 502,
        description: "Horizon API fallback endpoint returned 500 error",
    },
    ErrorDetail {
        code: 7008,
        mnemonic: "INVALID_BASE64_PAYLOAD",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Supplied string is not valid standard Base64 encoding",
    },
    ErrorDetail {
        code: 7009,
        mnemonic: "UNSUPPORTED_NETWORK_PASSPHRASE",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Network passphrase not recognized (expected testnet or public)",
    },
    ErrorDetail {
        code: 7010,
        mnemonic: "CONTRACT_ABI_NOT_FOUND",
        domain: ErrorDomain::ClientSdk,
        http_status: 404,
        description: "Contract specification stream missing from WASM binary",
    },
    ErrorDetail {
        code: 7011,
        mnemonic: "JSON_SERIALIZATION_FAILED",
        domain: ErrorDomain::ClientSdk,
        http_status: 500,
        description: "Failed to serialize JavaScript object to JSON string",
    },
    ErrorDetail {
        code: 7012,
        mnemonic: "FREIGHTER_NOT_INSTALLED",
        domain: ErrorDomain::ClientSdk,
        http_status: 404,
        description: "Freighter wallet browser extension was not detected",
    },
    ErrorDetail {
        code: 7013,
        mnemonic: "USER_REJECTED_SIGNATURE",
        domain: ErrorDomain::ClientSdk,
        http_status: 403,
        description: "User declined signature prompt in wallet popup",
    },
    ErrorDetail {
        code: 7014,
        mnemonic: "UNSUPPORTED_WALLET_PROVIDER",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Selected wallet provider is not supported in this browser",
    },
    ErrorDetail {
        code: 7015,
        mnemonic: "SOCKET_CONNECTION_CLOSED",
        domain: ErrorDomain::ClientSdk,
        http_status: 503,
        description: "WebSocket connection for real-time ledger streaming closed unexpectedly",
    },
    ErrorDetail {
        code: 7016,
        mnemonic: "PARSING_INT128_FAILED",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Failed to parse string into 128-bit big integer",
    },
    ErrorDetail {
        code: 7017,
        mnemonic: "CONFIG_NOT_LOADED",
        domain: ErrorDomain::ClientSdk,
        http_status: 500,
        description: "SafeguardClient initialized without required configuration",
    },
    ErrorDetail {
        code: 7018,
        mnemonic: "LEDGER_HISTORY_UNAVAILABLE",
        domain: ErrorDomain::ClientSdk,
        http_status: 404,
        description: "Target ledger sequence is beyond RPC node history retention",
    },
    ErrorDetail {
        code: 7019,
        mnemonic: "EVENT_SUBSCRIPTION_FAILED",
        domain: ErrorDomain::ClientSdk,
        http_status: 502,
        description: "Failed to subscribe to contract topic events via RPC filter",
    },
    ErrorDetail {
        code: 7020,
        mnemonic: "BATCH_PAYMENT_SIZE_LIMIT",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Batch payment array exceeds client maximum size of 50 items",
    },
    ErrorDetail {
        code: 7021,
        mnemonic: "RESPONSE_SCHEMA_VALIDATION_ERROR",
        domain: ErrorDomain::ClientSdk,
        http_status: 500,
        description: "Server response payload did not conform to Zod schema",
    },
    ErrorDetail {
        code: 7022,
        mnemonic: "METHOD_NOT_FOUND_ON_CONTRACT",
        domain: ErrorDomain::ClientSdk,
        http_status: 404,
        description: "Target method is not an exported function on contract",
    },
    ErrorDetail {
        code: 7023,
        mnemonic: "IDEMPOTENCY_KEY_MISSING",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "POST request requires unique Idempotency-Key header",
    },
    ErrorDetail {
        code: 7024,
        mnemonic: "IDEMPOTENCY_CONFLICT",
        domain: ErrorDomain::ClientSdk,
        http_status: 409,
        description: "Request with same Idempotency-Key is currently being processed",
    },
    ErrorDetail {
        code: 7025,
        mnemonic: "SDK_VERSION_DEPRECATED",
        domain: ErrorDomain::ClientSdk,
        http_status: 426,
        description: "Client SDK version is below required minimum protocol version",
    },
    ErrorDetail {
        code: 7026,
        mnemonic: "INVALID_HEX_STRING",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "String is not a valid even-length hexadecimal string",
    },
    ErrorDetail {
        code: 7027,
        mnemonic: "INSUFFICIENT_FEE_ESTIMATE",
        domain: ErrorDomain::ClientSdk,
        http_status: 400,
        description: "Simulated fee is higher than client max fee setting",
    },
    ErrorDetail {
        code: 7028,
        mnemonic: "TRANSACTION_ABORTED",
        domain: ErrorDomain::ClientSdk,
        http_status: 499,
        description: "Transaction execution was cancelled by caller before submission",
    },
    ErrorDetail {
        code: 7029,
        mnemonic: "UNKNOWN_CLIENT_ERROR",
        domain: ErrorDomain::ClientSdk,
        http_status: 500,
        description: "Unclassified client SDK runtime exception",
    },
    ErrorDetail {
        code: 8000,
        mnemonic: "AUDIT_LOG_TAMPERED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Cryptographic hash chain verification failed on audit records",
    },
    ErrorDetail {
        code: 8001,
        mnemonic: "HASH_CHAIN_BROKEN",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Previous block digest pointer does not match parent record hash",
    },
    ErrorDetail {
        code: 8002,
        mnemonic: "SEQUENCE_GAP_DETECTED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Audit sequence counter skipped an integer index",
    },
    ErrorDetail {
        code: 8003,
        mnemonic: "PROOF_VERIFICATION_FAILED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 422,
        description: "Merkle inclusion proof verification failed against batch root",
    },
    ErrorDetail {
        code: 8004,
        mnemonic: "STORAGE_PROOF_INVALID",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 422,
        description: "State commitment proof does not match Stellar ledger state",
    },
    ErrorDetail {
        code: 8005,
        mnemonic: "AUDIT_EVIDENCE_EXPIRED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 410,
        description: "Evidence retention window has lapsed for audit package",
    },
    ErrorDetail {
        code: 8006,
        mnemonic: "EVIDENCE_CHECKSUM_MISMATCH",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 400,
        description: "Evidence package archive checksum does not match manifest",
    },
    ErrorDetail {
        code: 8007,
        mnemonic: "UNAUTHORIZED_AUDITOR",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 401,
        description: "Signer does not hold the certified Independent Auditor credential",
    },
    ErrorDetail {
        code: 8008,
        mnemonic: "REPORT_ALREADY_FINALIZED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 409,
        description: "Audit report has been signed and sealed into immutable state",
    },
    ErrorDetail {
        code: 8009,
        mnemonic: "INTEGRITY_ATTESTATION_FAILED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Hardware enclave or TEE attestation failed signature check",
    },
    ErrorDetail {
        code: 8010,
        mnemonic: "EVENT_DIGEST_MISMATCH",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Emitted event payload hash does not match logged audit entry",
    },
    ErrorDetail {
        code: 8011,
        mnemonic: "MISSING_PREDECESSOR_BLOCK",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 404,
        description: "Audit chain checkpoint references missing historical segment",
    },
    ErrorDetail {
        code: 8012,
        mnemonic: "TIMESTAMP_NON_MONOTONIC",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 400,
        description: "Audit record timestamp is earlier than preceding record",
    },
    ErrorDetail {
        code: 8013,
        mnemonic: "REPRODUCIBLE_REPORT_FAILURE",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Deterministic rerun of policy verification produced differing result",
    },
    ErrorDetail {
        code: 8014,
        mnemonic: "REGULATOR_PACKAGE_SEAL_BROKEN",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 500,
        description: "Digital signature seal on regulatory compliance export is invalid",
    },
    ErrorDetail {
        code: 8015,
        mnemonic: "AUDIT_VAULT_CAPACITY_REACHED",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 507,
        description: "On-chain audit accumulator reached maximum capacity",
    },
    ErrorDetail {
        code: 8016,
        mnemonic: "RECORD_LOCKED_FOR_DISCOVERY",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 423,
        description: "Record cannot be purged while legal discovery freeze is active",
    },
    ErrorDetail {
        code: 8017,
        mnemonic: "UNSUPPORTED_DIGEST_ALGORITHM",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 400,
        description: "Hash algorithm is not supported (expected SHA-256 or BLAKE3)",
    },
    ErrorDetail {
        code: 8018,
        mnemonic: "DISPUTE_PROOF_INSUFFICIENT",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 422,
        description: "Submitted dispute proof does not contain sufficient state witnesses",
    },
    ErrorDetail {
        code: 8019,
        mnemonic: "AUDIT_INDEX_OUT_OF_SYNC",
        domain: ErrorDomain::AuditIntegrity,
        http_status: 503,
        description: "Secondary query index lags behind authoritative blockchain ledger",
    },
    ErrorDetail {
        code: 9000,
        mnemonic: "CONFIG_SCHEMA_MISMATCH",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 400,
        description: "Configuration object does not validate against target JSON schema",
    },
    ErrorDetail {
        code: 9001,
        mnemonic: "MISSING_ENVIRONMENT_VARIABLE",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 500,
        description: "Required environment variable is undefined in execution context",
    },
    ErrorDetail {
        code: 9002,
        mnemonic: "CONTRACT_NOT_INITIALIZED",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 503,
        description: "Contract deployed but initialize() has not been executed",
    },
    ErrorDetail {
        code: 9003,
        mnemonic: "INCOMPATIBLE_PROTOCOL_VERSION",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 426,
        description: "Ledger protocol version is below required minimum (Protocol 22)",
    },
    ErrorDetail {
        code: 9004,
        mnemonic: "INVALID_NETWORK_NAME",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 400,
        description: "Network name must be one of: testnet, futurenet, mainnet, standalone",
    },
    ErrorDetail {
        code: 9005,
        mnemonic: "RPC_PORT_CONFLICT",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 500,
        description: "Local sandbox RPC port is already bound by another process",
    },
    ErrorDetail {
        code: 9006,
        mnemonic: "WASM_HASH_NOT_REGISTERED",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 404,
        description: "WASM binary hash not found in on-chain code repository",
    },
    ErrorDetail {
        code: 9007,
        mnemonic: "DEPLOYMENT_ALREADY_EXISTS",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 409,
        description: "Contract instance already deployed at computed address",
    },
    ErrorDetail {
        code: 9008,
        mnemonic: "INVALID_DEPLOYMENT_SALT",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 400,
        description: "Salt must be a 32-byte hex string or alphanumeric identifier",
    },
    ErrorDetail {
        code: 9009,
        mnemonic: "UNRECOGNIZED_CHAIN_ID",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 400,
        description: "Chain ID does not correspond to a known Stellar cluster",
    },
    ErrorDetail {
        code: 9010,
        mnemonic: "SECRETS_VAULT_UNREACHABLE",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 503,
        description: "Unable to retrieve deployment private keys from secrets manager",
    },
    ErrorDetail {
        code: 9011,
        mnemonic: "DATABASE_MIGRATION_PENDING",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 503,
        description: "Database schema has pending migrations; refusing traffic",
    },
    ErrorDetail {
        code: 9012,
        mnemonic: "STORAGE_BACKEND_UNAVAILABLE",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 503,
        description: "Persistent storage engine (Postgres / Redis) connection failed",
    },
    ErrorDetail {
        code: 9013,
        mnemonic: "CORRUPT_ENV_FILE",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 500,
        description: "Syntax error encountered while parsing .env configuration file",
    },
    ErrorDetail {
        code: 9014,
        mnemonic: "DEPLOYMENT_METADATA_MISSING",
        domain: ErrorDomain::ConfigDeployment,
        http_status: 404,
        description: "deployments/testnet.json file not found in repository root",
    }
];

pub fn lookup_error(code: u32) -> Option<&'static ErrorDetail> {
    ERROR_CATALOG.iter().find(|e| e.code == code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_catalog_has_expected_count() {
        assert_eq!(ERROR_CATALOG.len(), 270);
        assert!(TOTAL_ERROR_CODES >= 250);
    }

    #[test]
    fn test_error_codes_are_unique_and_sorted() {
        for i in 1..ERROR_CATALOG.len() {
            assert!(
                ERROR_CATALOG[i].code > ERROR_CATALOG[i - 1].code,
                "Duplicate or unsorted code: {}",
                ERROR_CATALOG[i].code
            );
        }
    }

    #[test]
    fn test_lookup_error() {
        let err = lookup_error(2001).expect("code 2001 should exist");
        assert_eq!(err.mnemonic, "POLICY_NOT_FOUND");
    }
}
